name: Build and Deploy Kai Chronicles
run-name: ${{ github.actor }} is building Kai Chronicles
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Build project
        run: |
          git config --global pack.threads "1"
          npm install
          npm run downloaddata --url=${{ vars.REPO_URL }}
          npm run test --kaibook=1 --kaisect=tssf
          npm run dist
      - name: Summarize Tests
        run: npx github-actions-ctrf ctrf/ctrf-report.json
      - name: Archive dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  deploy:
    needs: build

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: /tmp/kaiChronicles/dist
      - name: P-SFTP
        uses: Luis97lol/PSFTP@v1.4
        with:
          # Remote SFTP Host
          host: ${{ secrets.SFTP_HOST }}
          # Session Username
          user: ${{ secrets.SFTP_USER }}
          # Session Password
          pass: ${{ secrets.SFTP_PASS }}
          # Optional hostkey if not cached
          hostkey: XXX
          # Path to the file that contains the psftp commands to be executed
          scriptPath: deploy.sh
          
