name: Build and Deploy Kai Chronicles
run-name: ${{ github.actor }} is building Kai Chronicles
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Build project
        run: |
          git config --global pack.threads "1"
          npm install
          npm run downloaddata --url=${{ vars.REPO_URL }}
          npm run dist
      - name: Summarize Tests
        run: npx github-actions-ctrf ctrf/ctrf-report.json
      - name: Archive dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  deploy:
    needs: build

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: /tmp/kaiChronicles/dist
      - name: Display structure of downloaded files
        run: ls -R /tmp/kaiChronicles/dist
      - name: Deploy files to Project Aon
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.SFTP_USER }}  
            server: ${{ secrets.SFTP_HOST }}
            password: ${{ secrets.SFTP_PASS }}
            
            local_path: "/tmp/kaiChronicles/dist/*"
            remote_path: "/"

